def Articles():

    posts = [
        {"title": "First Article",
         "content": "This is just a dummy data",
         "author": "sam",
         "likes": "28",
         "id": 0},
        {"title": "Second Article",
         "content": "This is just another dummy data",
         "author": "samperfect",
         "likes": "12",
         "id": 1},
        {"title": "First Article",
         "content": "This is just a dummy data",
         "author": "samperfect",
         "likes": "1",
         "id": 2},
        {"title": "Second Article",
         "content": "This is just another dummy data",
         "author": "sam",
         "likes": "2",
         "id": 3},
        {"title": "First Article",
         "content": "This is just a dummy data",
         "author": "samperfect",
         "likes": "0",
         "id": 4},
        {"title": "First Article",
         "content": "This is just a dummy data",
         "author": "samperfect",
         "likes": "1",
         "id": 5},
        {"title": "Second Article",
         "content": "This is just another dummy data",
         "author": "sam",
         "likes": "2",
         "id": 6},
        {"title": "First Article",
         "content": "This is just a dummy data",
         "author": "samperfect",
         "likes": "0",
         "id": 7}
    ]

    return posts
