"""empty message

Revision ID: 3d8607c22a1b
Revises: 51382a68684f
Create Date: 2021-01-06 21:00:12.453859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8607c22a1b'
down_revision = '51382a68684f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_story_date_posted'), 'story', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_date_posted'), table_name='story')
    # ### end Alembic commands ###
