"""empty message

Revision ID: a613d7c73196
Revises: 3d8607c22a1b
Create Date: 2021-01-08 17:17:03.704154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a613d7c73196'
down_revision = '3d8607c22a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_collection_date_added'), 'collection', ['date_added'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_date_added'), table_name='collection')
    op.drop_column('collection', 'date_added')
    # ### end Alembic commands ###
